# print("Welcome to the Band Name Generator.\nWhat's the name of the city you grew up in? ")
# city = input()
# print("What's your pet's name?")
# pet = input()
# print("Your band name could be " + city + " " + pet + "!")

print("Welcome to the Band Name Generator!!")
food = input("What is your least favorite food? ")
drink = input("What is your favorite drink? ")
print("Your band name could be " + food + " 'n " + drink + "!")